name: Groovy CI

on:
  - push
  - pull_request
  - workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Validate Gradle
      uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
    - name: Retrieve Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Grant permission to execute Gradle
      run: chmod +x ./gradlew
    - name: Build Artifacts
      run: ./gradlew build
    - name: Find artifacts
      id: find-artifacts
      run: |
          output="$(find build/libs/ ! -name "*-javadoc.jar" ! -name "*-sources.jar" -type f -printf "%f\n")"
          echo "artifact=$output" >> $GITHUB_OUTPUT
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Compiled artifacts for ${{ github.sha }}
        path: build/libs
