name: Gradle CD

on:
  release:
    types: [published]
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Validate Gradle
      uses: gradle/wrapper-validation-action@v1
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
    - name: Retrieve Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Grant permission to execute Gradle
      run: chmod +x ./gradlew
    - name: Build Artifacts
      run: ./gradlew build
    - name: Find artifacts
      id: find-artifacts
      run: |
          output="$(find build/libs/ ! -name "*-javadoc.jar" ! -name "*-sources.jar" -type f -printf "%f\n")"
          echo "artifact=$output" >> $GITHUB_OUTPUT
    - name: Upload to the Github release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: build/libs/${{ steps.find-artifacts.outputs.artifact }}
        asset_name: ${{ steps.find-artifacts.outputs.artifact }}
        asset_content_type: application/java-archive